
<style type="text/css">
    #view-content{
        width:40%;      
        margin:auto;
        margin-top: 150px;
    }
    
</style>
<div id="view-content">
    <form method="post" enctype="multipart/form-data" action="Did/upload">
        <table>
            <tbody>
                <tr>
                <td colspan="2">
                    <input type="file" name="inFile" id="file-upload" required/>
                </td>
                </tr>
                <tr>
                <td align="left">
                     <input type="submit" value="Upload" />
                </td>
                <td align="right">
                    <input type="button" value="Manage / Add Manually" />
                </td>
                </tr>
            </tbody>
        </table>
           
            
            
 
    </form>
</div>